#spring.application.name=dubbo-provider
server:
    port: 8100
spring:
    dubbo:
        scan: com.example.demo.demoproducer.server
        application:
            id: auth-branch
            name: auth-branch
            logger: slf4j
        registry:
            address: zookeeper://127.0.0.1:2181
            file: cache
        protocol:
            #id: dubbo
            name: dubbo
            port: 20881
            #status : server
        server: true